### ISSUE TITLE
npx npm run в package.json

### ISSUE THREAD

**Issue by AntiHero** [avpeshkov/my-react-js-tutorial#8]
не первый раз замечаю у ребят и у тебя в том числе npx, npm run в cкриптах package.json, убирай их, они не нужны,
вместо `npm run fix-style && npm run lint && npm test && npm run test:loki && git add .` 
просто пишешь  `fix-style && lint && test && test:loki && git add .`

**Comment by avpeshkov** [comment]
проверил вариант такая запись вызвает ошибку:
`
avp@avp-hm:~/study/my-react-js-tutorial$ git commit -m "[ft/lesson-10-homework] добавлены alias для webpack и jest, JSDoc"
husky > pre-commit (node v14.12.0)
✔ Preparing...
✔ Hiding unstaged changes to partially staged files...
⚠ Running tasks...
  ❯ Running tasks for *.{ts,tsx}
    ✖ npm run pre-commit-check [FAILED]
  ↓ No staged files match *.scss [SKIPPED]
↓ Skipped because of errors from tasks. [SKIPPED]
↓ Skipped because of errors from tasks. [SKIPPED]
✔ Reverting to original state because of errors...
✔ Cleaning up... 

✖ npm run pre-commit-check:
sh: 1: fix-style: not found
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! react-js-tutorial@1.0.0 pre-commit-check: `fix-style && lint && test && test:loki && git add . "/home/avp/study/my-react-js-tutorial/src/components/MainScreen/MainScreen.tsx" "/home/avp/study/my-react-js-tutorial/src/components/MoodForm/MoodForm.stories.tsx" "/home/avp/study/my-react-js-tutorial/src/components/MoodForm/MoodForm.test.tsx" "/home/avp/study/my-react-js-tutorial/src/components/MoodForm/MoodForm.tsx" "/home/avp/study/my-react-js-tutorial/src/components/MoodHistory/MoodHistory.stories.tsx" "/home/avp/study/my-react-js-tutorial/src/components/MoodHistory/MoodHistory.test.tsx" "/home/avp/study/my-react-js-tutorial/src/components/MoodHistory/MoodHistory.tsx" "/home/avp/study/my-react-js-tutorial/src/components/MoodScale/MoodScale.tsx" "/home/avp/study/my-react-js-tutorial/src/components/MoodScale/components/MoodItem/MoodItem.tsx" "/home/avp/study/my-react-js-tutorial/src/components/MoodView/MoodView.stories.tsx" "/home/avp/study/my-react-js-tutorial/src/components/MoodView/MoodView.test.tsx" "/home/avp/study/my-react-js-tutorial/src/components/MoodView/MoodView.tsx" "/home/avp/study/my-react-js-tutorial/src/components/QuoteBlock/QuoteBlock.stories.tsx" "/home/avp/study/my-react-js-tutorial/src/components/QuoteBlock/QuoteBlock.tsx" "/home/avp/study/my-react-js-tutorial/src/components/QuoteBlock/QuteBlock.test.tsx" "/home/avp/study/my-react-js-tutorial/src/types/mood.ts"`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the react-js-tutorial@1.0.0 pre-commit-check script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/avp/.npm/_logs/2020-11-24T19_52_18_387Z-debug.log

> react-js-tutorial@1.0.0 pre-commit-check /home/avp/study/my-react-js-tutorial
> fix-style && lint && test && test:loki && git add . "/home/avp/study/my-react-js-tutorial/src/components/MainScreen/MainScreen.tsx" "/home/avp/study/my-react-js-tutorial/src/components/MoodForm/MoodForm.stories.tsx" "/home/avp/study/my-react-js-tutorial/src/components/MoodForm/MoodForm.test.tsx" "/home/avp/study/my-react-js-tutorial/src/components/MoodForm/MoodForm.tsx" "/home/avp/study/my-react-js-tutorial/src/components/MoodHistory/MoodHistory.stories.tsx" "/home/avp/study/my-react-js-tutorial/src/components/MoodHistory/MoodHistory.test.tsx" "/home/avp/study/my-react-js-tutorial/src/components/MoodHistory/MoodHistory.tsx" "/home/avp/study/my-react-js-tutorial/src/components/MoodScale/MoodScale.tsx" "/home/avp/study/my-react-js-tutorial/src/components/MoodScale/components/MoodItem/MoodItem.tsx" "/home/avp/study/my-react-js-tutorial/src/components/MoodView/MoodView.stories.tsx" "/home/avp/study/my-react-js-tutorial/src/components/MoodView/MoodView.test.tsx" "/home/avp/study/my-react-js-tutorial/src/components/MoodView/MoodView.tsx" "/home/avp/study/my-react-js-tutorial/src/components/QuoteBlock/QuoteBlock.stories.tsx" "/home/avp/study/my-react-js-tutorial/src/components/QuoteBlock/QuoteBlock.tsx" "/home/avp/study/my-react-js-tutorial/src/components/QuoteBlock/QuteBlock.test.tsx" "/home/avp/study/my-react-js-tutorial/src/types/mood.ts"

husky > pre-commit hook failed (add --no-verify to bypass)
`

**Comment by AntiHero** [comment]
да, извиняюсь, npm run надо оставить, а вот npx нет
